<a href="https://colab.research.google.com/github/SamariaSpringfield/MAT421_/blob/main/Section1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Linear Algebra and Systems of Linear Equations**

*Section 1.1-4*

In this section we will focus on linear relationships, a fundamental relationship in engineering and science alike.


**1.1 Basics of Linear Algebra**

Sets - Collection of objects {}

Union - A U B - Set containing all elements of A and B

Intersect - A n B - Set Containing all elements thats belong to both A and B

Naturals - N = {1,2,3,4,..}

Wholes - W = N U {0}

Integers - Z = W U {-1,-2,-3,....}

Rationals - Q = { p/g : p ∊ Z , q ∊ Z \ {0}}

Irrationals - I = set of real numbers not expressible as a fraction of integers

Reals - R = Q U I

Complex Numbers - C = {a + bi: a, b ∊ R, i = sqrt(-1) }


**Vectors**

**Example 1** Create a row vector and column vector, and show the shape of the vectors.

In [2]:

import numpy as np
vector_row = np.array([[7, -3, 3, 1, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


**Matrices**

**Example 2**  Use Python to find the determinant of the matrix 𝑀=[[0,5,1,4], [3,3,8,8], [1,2,0,3], [0,4,2,3]]. Use the np.eye function to produce a 4×4 identity matrix, 𝐼. Multiply 𝑀 by 𝐼 to show that the result is 𝑀.

In [3]:

from numpy.linalg import det

M = np.array([[0,5,1,4], 
             [3,3,8,8], 
             [1,2,0,3],
             [0,4,2,3]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))


M:
 [[0 5 1 4]
 [3 3 8 8]
 [1 2 0 3]
 [0 4 2 3]]
Determinant: -17.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 5. 1. 4.]
 [3. 3. 8. 8.]
 [1. 2. 0. 3.]
 [0. 4. 2. 3.]]
